DROP DATABASE IF EXISTS orchids_db;
CREATE DATABASE orchids_db;

USE orchids_db;

CREATE TABLE orchids(
	id INT NOT NULL AUTO_INCREMENT,
	# INT NOT NULL AUTO_INCREMENT,
	Genus VARCHAR(255) NOT NULL,
    Species VARCHAR(255) NOT NULL,
    Cultivar VARCHAR(255) NOT NULL,
    Notes VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);